#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-addthis-oss-jar-pom
Version  : 3.4.0
Release  : 1
URL      : https://github.com/addthis/addthis-oss-jar-pom/archive/v3.4.0.tar.gz
Source0  : https://github.com/addthis/addthis-oss-jar-pom/archive/v3.4.0.tar.gz
Source1  : http://repo1.maven.org/maven2/com/addthis/common/build/maven/pom/jar-pom/3.4.0/jar-pom-3.4.0.pom
Source2  : http://repo1.maven.org/maven2/com/addthis/common/build/maven/pom/papa-pom/2.1.0/papa-pom-2.1.0.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-addthis-oss-jar-pom-data = %{version}-%{release}
Requires: mvn-addthis-oss-jar-pom-license = %{version}-%{release}
BuildRequires : apache-maven
BuildRequires : buildreq-mvn

%description
# addthis-oss-jar-pom
## XML
[parent pom](http://maven.apache.org/guides/introduction/introduction-to-the-pom.html)
allows various defaults to be specified so that each individual
project does not repeat itself.  This is a pom for projects that build
jars.  It includes a variety of plugins for static analysis and builds
all artifacts (ie javadoc) necessary for acceptance to maven central.

%package data
Summary: data components for the mvn-addthis-oss-jar-pom package.
Group: Data

%description data
data components for the mvn-addthis-oss-jar-pom package.


%package license
Summary: license components for the mvn-addthis-oss-jar-pom package.
Group: Default

%description license
license components for the mvn-addthis-oss-jar-pom package.


%prep
%setup -q -n addthis-oss-jar-pom-3.4.0

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-addthis-oss-jar-pom
cp LICENSE %{buildroot}/usr/share/package-licenses/mvn-addthis-oss-jar-pom/LICENSE
cp NOTICE %{buildroot}/usr/share/package-licenses/mvn-addthis-oss-jar-pom/NOTICE
mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/addthis/common/build/maven/pom/jar-pom/3.4.0
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/com/addthis/common/build/maven/pom/jar-pom/3.4.0/jar-pom-3.4.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/addthis/common/build/maven/pom/papa-pom/2.1.0
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/com/addthis/common/build/maven/pom/papa-pom/2.1.0/papa-pom-2.1.0.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/com/addthis/common/build/maven/pom/jar-pom/3.4.0/jar-pom-3.4.0.pom
/usr/share/java/.m2/repository/com/addthis/common/build/maven/pom/papa-pom/2.1.0/papa-pom-2.1.0.pom

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-addthis-oss-jar-pom/LICENSE
/usr/share/package-licenses/mvn-addthis-oss-jar-pom/NOTICE
